rubikscomplex\model\Question:
  type: entity
  table: questions
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    identifier:      { type: string, unique: true }
    prompt:          { type: text }
    correct_answer:  { type: integer }
    answer_type:     { type: integer }
    explanation:     { type: text }
    number:          { type: integer }

  oneToMany:
    answers:
      targetEntity: rubikscomplex\model\Answer
      mappedBy: question
      cascade: [ "delete" ]

  manyToOne:
    test:
      targetEntity: rubikscomplex\model\Test
      inversedBy: questions
