rubikscomplex\model\Answer:
  type: entity
  table: answers
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    text: { type: text }
    question_index: { type: integer }
    
  manyToOne:
    question:
      targetEntity: rubikscomplex\model\Question
      inversedBy: answers

