rubikscomplex\model\UserPasswordEmail:
  type: entity
  table: user_password_emails
  id:
    id:
      unique: true
      type: integer
      generator:
        strategy: AUTO

  fields:
    email:       { type: string, length: 255 }
    token:       { type: string, length: 255 }
    sent_time:   { type: datetime }
    expiry_time: { type: datetime }
    used:        { type: boolean }

  manyToOne:
    user:
      targetEntity: User
      inversedBy: password_reset_emails
